# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: D:/univrsity/CAlab/CA-LAB/trunk/src/hdl/pin_assignment.xdc

# Block Designs: bd/design_1/design_1.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1 || ORIG_REF_NAME==design_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_IF_stage_0_1/design_1_IF_stage_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_IF_stage_0_1 || ORIG_REF_NAME==design_1_IF_stage_0_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_ID_stage_reg_0_0/design_1_ID_stage_reg_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_ID_stage_reg_0_0 || ORIG_REF_NAME==design_1_ID_stage_reg_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_IF_stage_reg_0_8/design_1_IF_stage_reg_0_8.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_IF_stage_reg_0_8 || ORIG_REF_NAME==design_1_IF_stage_reg_0_8} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xlconstant_0_0/design_1_xlconstant_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_xlconstant_0_0 || ORIG_REF_NAME==design_1_xlconstant_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xlslice_0_0/design_1_xlslice_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_xlslice_0_0 || ORIG_REF_NAME==design_1_xlslice_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_ID_stage_0_1/design_1_ID_stage_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_ID_stage_0_1 || ORIG_REF_NAME==design_1_ID_stage_0_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_dist_mem_gen_0_0/design_1_dist_mem_gen_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_dist_mem_gen_0_0 || ORIG_REF_NAME==design_1_dist_mem_gen_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_EXE_stage_0_0/design_1_EXE_stage_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_EXE_stage_0_0 || ORIG_REF_NAME==design_1_EXE_stage_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_StatusRgister_0_0/design_1_StatusRgister_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_StatusRgister_0_0 || ORIG_REF_NAME==design_1_StatusRgister_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_ila_0_0/design_1_ila_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_ila_0_0 || ORIG_REF_NAME==design_1_ila_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_debouncer_0_0/design_1_debouncer_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_debouncer_0_0 || ORIG_REF_NAME==design_1_debouncer_0_0} -quiet] -quiet

# XDC: bd/design_1/design_1_ooc.xdc
