set_property SRC_FILE_INFO {cfile:D:/univrsity/CAlab/CA-LAB/trunk/src/hdl/pin_assignment.xdc rfile:../../../../pin_assignment.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:6 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN U18                [get_ports clk_0]
set_property src_info {type:XDC file:1 line:11 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN J15                [get_ports rst_0]
